"""place group

Revision ID: 20b9caddd3ec
Revises: 47a6becb2f1c
Create Date: 2015-01-20 00:09:08.507607

"""

# revision identifiers, used by Alembic.
revision = '20b9caddd3ec'
down_revision = '47a6becb2f1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('group', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_place_group'), 'place', ['group'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_group'), table_name='place')
    op.drop_column('place', 'group')
    ### end Alembic commands ###
