"""init

Revision ID: 2facafaefd48
Revises: None
Create Date: 2015-01-17 16:10:17.740129

"""

# revision identifiers, used by Alembic.
revision = '2facafaefd48'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_latitude'), 'place', ['latitude'], unique=False)
    op.create_index(op.f('ix_place_longitude'), 'place', ['longitude'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_longitude'), table_name='place')
    op.drop_index(op.f('ix_place_latitude'), table_name='place')
    op.drop_table('place')
    ### end Alembic commands ###
