"""account

Revision ID: 47a6becb2f1c
Revises: 2facafaefd48
Create Date: 2015-01-17 20:05:24.358690

"""

# revision identifiers, used by Alembic.
revision = '47a6becb2f1c'
down_revision = '2facafaefd48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('salt', sa.String(length=6), nullable=False),
    sa.Column('salted', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    ### end Alembic commands ###
